(function(){
'use strict';
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const DAYS=['D','L','M','X','J','V','S'], DAY_NAMES=['domingo','lunes','martes','miércoles','jueves','viernes','sábado'];
const PERIODS={morning:'Mañana',afternoon:'Tarde',night:'Noche'};
const DIFFICULTIES={easy:'Suave',medium:'Normal',hard:'Un reto'};
const DAILY_PHRASES=window.SPIDIDAY_QUOTES||[];
const DEFAULT_CATEGORIES=['Alimentación','Transporte','Hogar','Salud','Ocio','Otros'];
let state={routines:[],completions:[],expenses:[],categories:[],settings:[]};
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const localDate=(d=new Date())=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const setting=id=>state.settings.find(x=>x.id===id)?.value;
let toastTimer,habitEditorOpener=null,habitEditorPreviousOverflow='',dailyPhraseIndex=-1;
function phraseSeed(){return [...localDate()].reduce((total,char)=>total+char.charCodeAt(0),0)%DAILY_PHRASES.length}
function renderDailyPhrase(change=false){if(dailyPhraseIndex<0)dailyPhraseIndex=phraseSeed();else if(change){let next=dailyPhraseIndex;while(next===dailyPhraseIndex)next=Math.floor(Math.random()*DAILY_PHRASES.length);dailyPhraseIndex=next}const phrase=DAILY_PHRASES[dailyPhraseIndex];$('#todaySummary').textContent=`“${phrase.text}”`;$('#todayPhraseSource').textContent=phrase.source}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function dateLabel(date){return new Intl.DateTimeFormat('es-CO',{day:'numeric',month:'short'}).format(new Date(date+'T12:00:00'))}
function routinesFor(date){const d=new Date(date+'T12:00:00').getDay();return state.routines.filter(r=>r.days.includes(d)&&(!r.createdAt||localDate(new Date(r.createdAt))<=date)&&(!r.archivedAt||localDate(new Date(r.archivedAt))>date));}
function isDone(routineId,date){return state.completions.some(c=>c.routineId===routineId&&c.date===date)}
function shortStatus(routineId,date){return (state.shortHabitCompletions||[]).find(c=>c.routineId===routineId&&c.date===date)?.status||''}
function progressFor(date){const list=routinesFor(date);return list.length?Math.round(list.filter(r=>isDone(r.id,date)).length/list.length*100):0}
function totalXp(){return state.completions.reduce((sum,c)=>sum+Number(state.routines.find(r=>r.id===c.routineId)?.xp||20),0)}
function streak(){let count=0;for(let i=0;i<365;i++){const d=new Date();d.setDate(d.getDate()-i);const date=localDate(d),list=routinesFor(date);if(!list.length){if(i===0)continue;break}if(progressFor(date)===100)count++;else if(i>0||state.completions.some(c=>c.date===date))break}return count}
async function refresh(){for(const name of AdriDB.STORES)state[name]=await AdriDB.all(name);renderAll();document.dispatchEvent(new CustomEvent('marea:data-refreshed'))}

function renderAll(){renderToday();renderRoutines();renderExpenses();renderProgress();renderSettings();}
function setMascotState(next){const stage=$('#pulseStage'),object=$('#mascotObject');stage.dataset.state=next;const sync=()=>{const root=object.contentDocument?.documentElement;if(root)root.dataset.state=next};sync();object.onload=sync}
function celebrateMascot(){const object=$('#mascotObject'),root=object.contentDocument?.documentElement;if(root){root.classList.add('celebrate');setTimeout(()=>root.classList.remove('celebrate'),560)}}
function routineHtml(r,date,editable=false){const done=isDone(r.id,date),partial=shortStatus(r.id,date),name=esc(r.name),status=done?'':partial==='completed'?' · Versión corta':partial==='omitted'?' · Omitido por hoy':'',meta=`${r.time?esc(r.time)+' · ':''}${PERIODS[r.period]} · ${DIFFICULTIES[r.difficulty]||'Normal'}${status}`;if(editable)return `<div class="routine-item ${done?'done':partial?'partial':''}"><input class="check" type="checkbox" aria-label="Completar ${name}" data-complete="${r.id}" data-date="${date}" ${done?'checked':''}><div class="item-main"><strong>${name}</strong><small>${meta}</small></div><button class="more" data-routine-menu="${r.id}" aria-label="Opciones de ${name}">•••</button></div>`;return `<div class="routine-item today-habit ${done?'done':partial?'partial':''}"><span class="habit-marker" aria-hidden="true"><i></i></span><div class="item-main"><strong>${name}</strong><small>${meta}</small></div><button class="complete-action" data-complete="${r.id}" data-date="${date}" data-done="${done}" aria-pressed="${done}" aria-label="${done?'Marcar como pendiente':'Completar'} ${name}"><i class="action-check" aria-hidden="true"></i><span>${done?'Completado':partial==='completed'?'Completar del todo':'Completar'}</span></button></div>`}
function groupedRoutines(list,date,editable=false){if(!list.length)return '<div class="card empty">Este espacio está libre por ahora.</div>';return ['morning','afternoon','night'].map(p=>{const rows=list.filter(r=>r.period===p).sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'));return rows.length?`<div class="routine-group"><h3 class="group-title">${PERIODS[p]}</h3><div class="card">${rows.map(r=>routineHtml(r,date,editable)).join('')}</div></div>`:''}).join('')}
function renderToday(){const now=new Date(),date=localDate(now),list=routinesFor(date),done=list.filter(r=>isDone(r.id,date)).length,p=progressFor(date),hour=now.getHours();let message='Sin prisa, empieza cuando quieras.',state=hour>=21?'rest':'calm';if(p===100&&list.length){message='Todo listo por hoy.';state='complete'}else if(p>=80){message='Ya casi está.';state='almost'}else if(p>=41){message='Vas a muy buen ritmo.';state='lively'}else if(p>0){message='Tu día está tomando forma.';state='awake'}$('#todayLabel').textContent=new Intl.DateTimeFormat('es-CO',{weekday:'long',day:'numeric',month:'long'}).format(now);$('#todayPercent').textContent=p+'%';$('#pulseStage').style.setProperty('--day-progress',p+'%');$('#todayMissionCount').textContent=list.length?`${done} de ${list.length} momentos completados`:'Aún no hay momentos para hoy.';$('#pulseProgress').textContent=list.length?`${done} de ${list.length} momentos completados`:'Un día abierto, a tu ritmo';$('#todayGreeting').textContent=hour<12?'Buenos días':hour<19?'Buenas tardes':'Buenas noches';renderDailyPhrase();$('#pulseMessage').textContent=p===0?'Tu día apenas comienza':message;setMascotState(state);$('#todayRoutines').innerHTML=groupedRoutines(list,date)}
function renderRoutines(){const today=localDate();$('#routineList').innerHTML=groupedRoutines(state.routines,today,true);let total=0,count=0;const cells=[];for(let i=29;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const date=localDate(d),p=progressFor(date),hasPartial=(state.shortHabitCompletions||[]).some(c=>c.date===date&&c.status==='completed');if(routinesFor(date).length){total+=p;count++}const level=p===0?(hasPartial?'partial':0):p<50?1:p<100?2:3;cells.push(`<span class="history-day" data-level="${level}" title="${dateLabel(date)}: ${p}%${hasPartial?' · recuperación parcial':''}"></span>`)}$('#historyGrid').innerHTML=cells.join('');$('#historyAverage').textContent=count?`Promedio ${Math.round(total/count)}%`:'Sin datos'}
function filteredExpenses(){const month=$('#monthSelect').value||localDate().slice(0,7),from=$('#filterFrom').value,to=$('#filterTo').value,cat=$('#filterCategory').value,pay=$('#filterPayment').value;return state.expenses.filter(e=>(!month||e.date.startsWith(month))&&(!from||e.date>=from)&&(!to||e.date<=to)&&(!cat||e.categoryId===cat)&&(!pay||e.payment===pay)).sort((a,b)=>b.date.localeCompare(a.date))}
function renderExpenses(){const months=new Set([localDate().slice(0,7),...state.expenses.map(e=>e.date.slice(0,7))]),select=$('#monthSelect'),chosen=select.value||localDate().slice(0,7);select.innerHTML=[...months].sort().reverse().map(m=>`<option value="${m}" ${m===chosen?'selected':''}>${new Intl.DateTimeFormat('es-CO',{month:'short',year:'numeric'}).format(new Date(m+'-02T12:00:00'))}</option>`).join('');const current=state.expenses.filter(e=>e.date.startsWith(localDate().slice(0,7))),spent=current.reduce((s,e)=>s+Number(e.amount),0),budget=Number(setting('budget'))||0,pct=budget?Math.round(spent/budget*100):0,remaining=budget-spent;$('#spentTotal').textContent=money(spent);$('#budgetRemaining').textContent=budget?`${remaining>=0?'Te quedan':'Te pasaste por'} ${money(Math.abs(remaining))}`:'Sin presupuesto';$('#budgetPercent').textContent=budget?pct+'%':'0%';$('#budgetBar').style.width=Math.min(pct,100)+'%';$('#budgetBar').classList.toggle('over',pct>100);$('#homeRemaining').textContent=budget?money(Math.max(0,remaining)):'Sin presupuesto';$('#homeBudgetState').textContent=budget?(pct>100?'Este mes pide un poco de calma.':pct>=85?'La marea está cerca del borde.':'Este mes todavía tienes margen.'):'Define un presupuesto para ver tu margen.';$('#homeTideWater').style.height=Math.min(Math.max(pct,8),100)+'%';if(budget>0&&pct>=85&&$('#pulseStage').dataset.state!=='complete')setMascotState('warning');const list=filteredExpenses(),sum=list.reduce((s,e)=>s+Number(e.amount),0),byCat={};list.forEach(e=>byCat[e.categoryId]=(byCat[e.categoryId]||0)+Number(e.amount));const grouped=Object.entries(byCat).sort((a,b)=>b[1]-a[1]);$('#homeCategoryDots').innerHTML=grouped.slice(0,3).map(([id,n],i)=>`<span class="category-dot"><i style="--dot:${['var(--coral)','var(--green)','var(--lavender)'][i]}"></i>${esc(state.categories.find(c=>c.id===id)?.name||'Otros')} · ${money(n)}</span>`).join('');$('#expenseCount').textContent=`${list.length} ${list.length===1?'apunte':'apuntes'}`;$('#categorySummary').innerHTML=list.length?grouped.map(([id,n])=>`<div class="category-bar"><span>${esc(state.categories.find(c=>c.id===id)?.name||'Sin categoría')}</span><i style="width:${sum?Math.max(5,n/sum*100):0}%"></i><strong>${money(n)}</strong></div>`).join(''):'<div class="empty">Todavía no hay gastos en este periodo.</div>';$('#expenseList').innerHTML=list.length?`<div class="card">${list.map(e=>`<div class="expense-item"><div class="item-main"><strong>${esc(e.description)}</strong><small>${dateLabel(e.date)} · ${esc(state.categories.find(c=>c.id===e.categoryId)?.name||'Sin categoría')} · ${esc(e.payment)}</small></div><span class="expense-amount">${money(e.amount)}</span><button class="more" data-expense-menu="${e.id}" aria-label="Opciones">•••</button></div>`).join('')}</div>`:'<div class="card empty">Cuando registres un gasto, aparecerá aquí.</div>';fillCategorySelects()}
function renderProgress(){const xp=totalXp(),level=Math.floor(xp/500)+1,completed=state.completions.length,perfect=[];for(let i=0;i<30;i++){const d=new Date();d.setDate(d.getDate()-i);const date=localDate(d);if(routinesFor(date).length&&progressFor(date)===100)perfect.push(date)}const current=state.expenses.filter(e=>e.date.startsWith(localDate().slice(0,7))),spent=current.reduce((s,e)=>s+Number(e.amount),0),budget=Number(setting('budget'))||0,budgetPct=budget?Math.round(spent/budget*100):null;$('#progressLevel').textContent=level;$('#rankName').textContent='Progreso personal';$('#progressXpText').textContent=`${xp} puntos de progreso`;$('#statStreak').textContent=streak();$('#statPerfect').textContent=perfect.length;$('#statCompleted').textContent=completed;$('#statBudget').textContent=budgetPct===null?'—':budgetPct+'%';const achievements=[['01','Primer paso',completed>=1],['02','Día redondo',perfect.length>=1],['03','Buen ritmo',completed>=10],['04','Mes cuidado',budgetPct!==null&&budgetPct<=100],['05','Constancia',completed>=25],['06','Siete seguidos',streak()>=7]];$('#achievementList').innerHTML=achievements.map(a=>`<div class="achievement ${a[2]?'unlocked':''}"><b>${a[0]}</b><span>${a[1]}</span></div>`).join('');const bars=[];for(let i=13;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const p=progressFor(localDate(d));bars.push(`<i class="chart-bar" style="height:${Math.max(3,p)}%" title="${p}%"></i>`)}$('#progressChart').innerHTML=bars.join('')}
function fillCategorySelects(){const options=state.categories.sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');const filter=$('#filterCategory'),v=filter.value;filter.innerHTML='<option value="">Todas</option>'+options;filter.value=v;const expense=$('#expenseForm select[name="categoryId"]'),ev=expense.value;expense.innerHTML=options||'<option value="">Crea una categoría primero</option>';expense.value=ev}
function renderSettings(){const last=setting('lastBackup');$('#lastBackup').textContent=`Última copia: ${last?new Intl.DateTimeFormat('es-CO',{dateStyle:'medium',timeStyle:'short'}).format(new Date(last)):'nunca'}`;$('#categoryList').innerHTML=state.categories.map(c=>`<div class="category-row"><span class="item-main">${esc(c.name)}</span><button class="more" data-category-menu="${c.id}" aria-label="Editar ${esc(c.name)}">•••</button></div>`).join('')||'<p class="muted">No hay categorías.</p>'}

async function toggleComplete(control){const id=`${control.dataset.date}:${control.dataset.complete}`,completed=control.matches('button')?control.dataset.done!=='true':control.checked;control.disabled=true;if(completed)await AdriDB.put('completions',{id,routineId:control.dataset.complete,date:control.dataset.date,completedAt:new Date().toISOString()});else await AdriDB.remove('completions',id);await refresh();if(completed){$('#pulseStage').classList.add('just-completed');celebrateMascot();setTimeout(()=>$('#pulseStage').classList.remove('just-completed'),560);toast(progressFor(control.dataset.date)===100?'Todo listo por hoy':'Un pequeño paso más')}else toast('Sin presión, puedes retomarlo cuando quieras')}
function closeHabitEditor(){const dialog=$('#routineDialog'),form=$('#routineForm'),opener=habitEditorOpener;dialog.classList.remove('open','active','visible');if(dialog.open)dialog.close();form.reset();form.elements.id.value='';$$('#dayPicker input').forEach(input=>input.checked=false);$('#daysError').textContent='';if(habitEditorPreviousOverflow)document.body.style.overflow=habitEditorPreviousOverflow;else document.body.style.removeProperty('overflow');habitEditorPreviousOverflow='';habitEditorOpener=null;if(opener?.isConnected)requestAnimationFrame(()=>opener.focus())}
function openRoutine(id){const f=$('#routineForm');habitEditorOpener=document.activeElement instanceof HTMLElement?document.activeElement:null;habitEditorPreviousOverflow=document.body.style.overflow;f.reset();f.elements.id.value='';$$('#dayPicker input').forEach(x=>x.checked=false);if(id){const r=state.routines.find(x=>x.id===id);f.elements.id.value=r.id;f.elements.name.value=r.name;f.elements.period.value=r.period;f.elements.time.value=r.time||'';f.elements.xp.value=r.xp||20;f.elements.difficulty.value=r.difficulty||'medium';$$('#dayPicker input').forEach(x=>x.checked=r.days.includes(Number(x.value)));$('#routineFormTitle').textContent='Editar hábito'}else{$('#routineFormTitle').textContent='Nuevo hábito';f.elements.xp.value=20;f.elements.difficulty.value='medium';[1,2,3,4,5].forEach(d=>$('#dayPicker input[value="'+d+'"]').checked=true)}$('#daysError').textContent='';document.body.style.overflow='hidden';$('#routineDialog').showModal()}
async function saveRoutine(e){e.preventDefault();const f=e.currentTarget,days=$$('#dayPicker input:checked').map(x=>Number(x.value)),xp=Number(f.elements.xp.value);if(!days.length){$('#daysError').textContent='Elige al menos un día.';return}if(!Number.isFinite(xp)||xp<5||xp>100){toast('El valor debe estar entre 5 y 100.');return}const existing=state.routines.find(r=>r.id===f.elements.id.value),item={id:f.elements.id.value||uid(),name:f.elements.name.value.trim(),period:f.elements.period.value,time:f.elements.time.value,xp,difficulty:f.elements.difficulty.value,days,createdAt:existing?.createdAt||new Date().toISOString()};if(!item.name){toast('Dale un nombre a este hábito.');return}await AdriDB.put('routines',item);closeHabitEditor();await refresh();toast('Hábito guardado')}
function openExpense(id){if(!state.categories.length){toast('Crea primero una categoría en Ajustes.');return}const f=$('#expenseForm');f.reset();f.elements.id.value='';f.elements.date.value=localDate();fillCategorySelects();if(id){const x=state.expenses.find(e=>e.id===id);Object.keys(x).forEach(k=>{if(f.elements[k])f.elements[k].value=x[k]});$('#expenseFormTitle').textContent='Editar gasto'}else $('#expenseFormTitle').textContent='Registrar gasto';$('#expenseDialog').showModal()}
async function saveExpense(e){e.preventDefault();const f=e.currentTarget,amount=Number(f.elements.amount.value),error=$('#amountError');error.textContent='';if(!Number.isFinite(amount)||amount<=0){error.textContent='Escribe un importe mayor que cero.';f.elements.amount.focus();return}if(!/^\d{4}-\d{2}-\d{2}$/.test(f.elements.date.value)){toast('Revisa la fecha del gasto.');return}await AdriDB.put('expenses',{id:f.elements.id.value||uid(),amount,categoryId:f.elements.categoryId.value,date:f.elements.date.value,description:f.elements.description.value.trim(),payment:f.elements.payment.value,updatedAt:new Date().toISOString()});f.closest('dialog').close();await refresh();toast('Gasto guardado')}
function openSimple(kind,id=''){const f=$('#simpleForm');f.reset();f.elements.kind.value=kind;f.elements.id.value=id;const input=f.elements.value;if(kind==='budget'){ $('#simpleTitle').textContent='Presupuesto mensual';$('#simpleLabel span').textContent='Importe';input.type='number';input.min='0';input.step='0.01';input.value=setting('budget')||''}else{const c=state.categories.find(x=>x.id===id);$('#simpleTitle').textContent=c?'Editar categoría':'Nueva categoría';$('#simpleLabel span').textContent='Nombre';input.type='text';input.removeAttribute('min');input.removeAttribute('step');input.maxLength=40;input.value=c?.name||''}$('#simpleDialog').showModal()}
async function saveSimple(e){e.preventDefault();const f=e.currentTarget,v=f.elements.value.value.trim();if(f.elements.kind.value==='budget'){if(Number(v)<0)return toast('El presupuesto no puede ser negativo.');await AdriDB.put('settings',{id:'budget',value:Number(v)||0})}else{if(!v)return toast('Escribe un nombre.');if(state.categories.some(c=>c.name.toLowerCase()===v.toLowerCase()&&c.id!==f.elements.id.value))return toast('Esa categoría ya existe.');await AdriDB.put('categories',{id:f.elements.id.value||uid(),name:v})}f.closest('dialog').close();await refresh();toast('Cambios guardados')}
async function itemMenu(type,id){const edit=confirm('Pulsa Aceptar para editar. Pulsa Cancelar para elegir si deseas eliminar.');if(edit){type==='routine'?openRoutine(id):type==='expense'?openExpense(id):openSimple('category',id);return}if(!confirm('¿Eliminar definitivamente este elemento? Esta acción no se puede deshacer.'))return;if(type==='category'&&state.expenses.some(e=>e.categoryId===id)){toast('No puedes eliminar una categoría con gastos asociados.');return}await AdriDB.remove(type==='routine'?'routines':type==='expense'?'expenses':'categories',id);if(type==='routine')for(const c of state.completions.filter(c=>c.routineId===id))await AdriDB.remove('completions',c.id);await refresh();toast('Elemento eliminado')}
function exportCsv(){const rows=[['Fecha','Importe','Categoría','Descripción','Método de pago'],...filteredExpenses().map(e=>[e.date,e.amount,state.categories.find(c=>c.id===e.categoryId)?.name||'',e.description,e.payment])];const csv='\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');download(`spididay-gastos-${localDate()}.csv`,csv,'text/csv;charset=utf-8')}
async function exportBackup(){const data=await AdriDB.exportAll(),payload={app:'SpidiDay',version:4,exportedAt:new Date().toISOString(),data};download(`spididay-copia-${localDate()}.json`,JSON.stringify(payload,null,2),'application/json');await AdriDB.put('settings',{id:'lastBackup',value:payload.exportedAt});await refresh();toast('Copia de seguridad exportada')}
function validBackup(x){const core=['routines','completions','expenses','categories','settings'];return x&&['AdriDay','SpidiDay'].includes(x.app)&&[1,2,3,4].includes(x.version)&&x.data&&core.every(s=>Array.isArray(x.data[s]))&&x.data.routines.every(r=>typeof r.id==='string'&&typeof r.name==='string'&&Array.isArray(r.days))&&x.data.expenses.every(e=>typeof e.id==='string'&&Number.isFinite(Number(e.amount))&&typeof e.date==='string')&&AdriDB.STORES.every(s=>x.data[s]===undefined||Array.isArray(x.data[s]))&&(x.data.verseJournalEntries===undefined||x.data.verseJournalEntries.every(entry=>typeof entry.id==='string'&&typeof entry.verseId==='string'&&typeof entry.reflection==='string'))}
async function importBackup(file){try{if(!file)return;const parsed=JSON.parse(await file.text());if(!validBackup(parsed))throw new Error('El archivo no tiene una estructura válida de AdriDay.');if(!confirm(`Se reemplazarán todos los datos actuales por la copia del ${new Intl.DateTimeFormat('es-CO',{dateStyle:'medium',timeStyle:'short'}).format(new Date(parsed.exportedAt))}. ¿Deseas continuar?`))return;await AdriDB.replaceAll(parsed.data);await refresh();toast('Copia restaurada correctamente')}catch(err){console.error(err);toast(err.message||'No se pudo importar la copia.')}finally{$('#importBackup').value=''}}
async function resetData(){if(!confirm('Esto borrará todos tus hábitos, gastos, progreso y ajustes de este dispositivo. ¿Continuar?'))return;if(!confirm('Última confirmación: esta operación no se puede deshacer sin una copia JSON.'))return;for(const name of AdriDB.STORES)await AdriDB.clear(name);for(const name of DEFAULT_CATEGORIES)await AdriDB.put('categories',{id:uid(),name});await refresh();toast('Todo listo para empezar de nuevo')}
function nav(view){$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${view}`));$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));scrollTo({top:0,behavior:'smooth'})}
async function init(){$('#todayPhraseNext').addEventListener('click',()=>renderDailyPhrase(true));try{await AdriDB.open();if(!(await AdriDB.all('categories')).length)for(const name of DEFAULT_CATEGORIES)await AdriDB.put('categories',{id:uid(),name});$('#dayPicker').innerHTML=DAYS.map((d,i)=>`<label title="${DAY_NAMES[i]}"><input type="checkbox" value="${i}"><span>${d}</span></label>`).join('');await refresh();if(navigator.storage?.persist){const persisted=await navigator.storage.persist();$('#storageStatus').textContent=persisted?'Almacenamiento persistente activado.':'El navegador administra el almacenamiento automáticamente.'}else $('#storageStatus').textContent='Almacenamiento local activado.'}catch(err){console.error(err);toast('No se pudo abrir el almacenamiento local.')}if('serviceWorker'in navigator)try{await navigator.serviceWorker.register('./service-worker.js')}catch(err){console.error('Service worker:',err)}}
document.addEventListener('click',e=>{const t=e.target.closest('button,[data-view],[data-close],[data-action]');if(!t)return;if(t.dataset.action==='close-habit-editor'||t.dataset.action==='cancel-habit-editor'){e.preventDefault();closeHabitEditor();return}if(t.matches('button[data-complete]')){toggleComplete(t);return}if(t.dataset.view){e.preventDefault();nav(t.dataset.view)}if(t.dataset.open==='routine')openRoutine();if(t.dataset.open==='expense')openExpense();if(t.hasAttribute('data-close')){e.preventDefault();t.closest('dialog')?.close()}if(t.dataset.routineMenu)itemMenu('routine',t.dataset.routineMenu);if(t.dataset.expenseMenu)itemMenu('expense',t.dataset.expenseMenu);if(t.dataset.categoryMenu)itemMenu('category',t.dataset.categoryMenu)});
document.addEventListener('change',e=>{if(e.target.matches('[data-complete]'))toggleComplete(e.target);if(e.target.matches('#monthSelect,#filterFrom,#filterTo,#filterCategory,#filterPayment'))renderExpenses()});
$('#routineForm').addEventListener('submit',saveRoutine);$('#routineDialog').addEventListener('cancel',e=>{e.preventDefault();closeHabitEditor()});$('#expenseForm').addEventListener('submit',saveExpense);$('#simpleForm').addEventListener('submit',saveSimple);$('#budgetButton').onclick=()=>openSimple('budget');$('#addCategory').onclick=()=>openSimple('category');$('#clearFilters').onclick=()=>{$$('#filterFrom,#filterTo,#filterCategory,#filterPayment').forEach(x=>x.value='');renderExpenses()};$('#exportCsv').onclick=exportCsv;$('#exportBackup').onclick=exportBackup;$('#importBackup').onchange=e=>importBackup(e.target.files[0]);$('#resetData').onclick=resetData;
function loadCompassFeature(){const verses=document.createElement('script');verses.src='./data/verses-rv1909.js';verses.onload=()=>{const feature=document.createElement('script');feature.src='./compass.js?v=15';feature.onerror=()=>toast('No se pudo abrir la Brújula.');document.body.append(feature)};verses.onerror=()=>toast('No se pudo cargar la palabra de hoy.');document.body.append(verses)}
window.MareaApp={refresh,toast,localDate,routinesFor,progressFor,isDone,nav,getState:()=>state};
window.addEventListener('focus',()=>{if($('#view-hoy').classList.contains('active'))refresh()});init();loadCompassFeature();
})();

