(function(){
'use strict';
const $=s=>document.querySelector(s), app=window.MareaApp, verses=window.RV1909_VERSES||[];
let currentVerse=null,currentVerseDate='',currentInsight=null,compassOpener=null,previousOverflow='',journalFilter='all',journalReturnView='ajustes',journalHighlightId='',journalDialogOpener=null,pendingDeleteId='',pendingShareId='',draftTimer=null;
const COLORS=['coral','verde','amarillo','lavanda'];

function injectInterface(){
  document.body.insertAdjacentHTML('beforeend',`<dialog id="compassDialog" class="compass-sheet"><section><div class="sheet-handle"></div><div class="dialog-head"><div><p class="overline">Brújula</p><h2 id="compassTitle">Hoy conviene hacerlo fácil.</h2></div><button type="button" class="round-btn" data-compass-close aria-label="Cerrar Brújula Marea">×</button></div><p class="compass-stage" id="compassStage">Todavía estoy conociendo tu ritmo.</p><p class="compass-copy" id="compassCopy"></p><div class="compass-short" id="compassShort" hidden><p id="compassShortText"></p><button class="primary" type="button" data-compass-action="complete-short">Completar versión corta</button></div><div class="compass-actions" id="compassActions"><button class="primary" type="button" data-compass-action="activate">Activar plan</button><button class="secondary" type="button" data-compass-action="short">Hacer versión corta</button><button class="text-action" type="button" data-compass-action="reject">No me sirve</button><button class="text-action omit-action" type="button" data-compass-action="omit">Omitir conscientemente por hoy</button></div><div class="compass-feedback" id="compassFeedbackPrompt" hidden><span>¿Te sirvió esta orientación?</span><button type="button" data-compass-action="helpful">Sí</button><button type="button" data-compass-action="unhelpful">No</button></div><button class="why-toggle" id="compassWhyToggle" type="button" aria-expanded="false">¿Por qué veo esto?</button><p class="compass-why" id="compassWhy" hidden></p><button class="sheet-cancel" type="button" data-compass-close>Cancelar</button></section></dialog>`);
  $('#compassDialog [data-compass-close]').setAttribute('aria-label','Cerrar Brújula SpidiDay');
  const target=[...document.querySelectorAll('#view-ajustes .profile-section')].find(section=>section.querySelector('h2')?.textContent==='Categorías');
  const journalLink=document.createElement('section');journalLink.className='profile-section journal-profile-link';journalLink.innerHTML=`<button type="button" class="journal-entry-link" data-open-journal><span><strong>Mi cuaderno</strong><small>Tus versículos y reflexiones guardadas</small></span><span aria-hidden="true">→</span></button>`;target?.before(journalLink);
  const main=document.querySelector('main');
  main.insertAdjacentHTML('beforeend',`<section class="view journal-view" id="view-cuaderno" aria-labelledby="journalTitle"><header class="journal-head"><button type="button" class="journal-back" data-close-journal aria-label="Volver a Perfil">←</button><p class="overline">Mi cuaderno</p><h1 id="journalTitle">Un espacio para volver a lo que te habló.</h1><p id="journalCount" class="journal-count">0 entradas</p></header><div id="journalTools" class="journal-tools" hidden><label>Buscar en tu cuaderno<input id="journalSearch" type="search" placeholder="Referencia, versículo o tus palabras"></label><div class="journal-filters" role="group" aria-label="Filtrar entradas"><button type="button" class="active" data-journal-filter="all">Todas</button><button type="button" data-journal-filter="reflection">Con reflexión</button><button type="button" data-journal-filter="favorite">Favoritas</button></div></div><div id="journalList"></div></section>`);
  document.body.insertAdjacentHTML('beforeend',`<dialog id="journalEditDialog" class="journal-sheet"><form id="journalEditForm"><div class="sheet-handle"></div><div class="dialog-head"><div><p class="overline">Mi cuaderno</p><h2>Editar reflexión</h2></div><button type="button" class="round-btn" data-close-journal-editor aria-label="Cerrar editor">×</button></div><blockquote id="journalEditVerse"></blockquote><input type="hidden" name="id"><label>Tu reflexión<textarea name="reflection" maxlength="1200" required></textarea></label><div class="actions"><button type="button" class="secondary" data-close-journal-editor>Cancelar</button><button type="submit" class="primary">Guardar cambios</button></div></form></dialog><dialog id="journalDeleteDialog" class="journal-sheet"><section><div class="sheet-handle"></div><h2>¿Eliminar esta reflexión?</h2><p>El versículo seguirá disponible en la colección bíblica, pero estas palabras se eliminarán de tu cuaderno.</p><div class="actions"><button type="button" class="secondary" data-close-journal-delete>Conservar</button><button type="button" class="danger-btn" data-confirm-journal-delete>Eliminar reflexión</button></div></section></dialog><dialog id="journalShareDialog" class="journal-sheet"><section><div class="sheet-handle"></div><h2>¿Qué quieres compartir?</h2><div class="stack"><button type="button" class="secondary" data-journal-share-choice="verse">Solo el versículo</button><button type="button" class="primary" data-journal-share-choice="both">Versículo y reflexión</button><button type="button" class="sheet-cancel" data-close-journal-share>Cancelar</button></div></section></dialog>`);
}

function seededRandom(seed){return function(){seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function annualOrder(year){const order=[...verses],random=seededRandom(year*7919+1909);for(let i=order.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[order[i],order[j]]=[order[j],order[i]]}return order}
function dayOfYear(date){return Math.floor((Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())-Date.UTC(date.getFullYear(),0,1))/86400000)}
function verseForDate(date=new Date()){return annualOrder(date.getFullYear())[dayOfYear(date)]}

const journalId=(verseId,date)=>`${verseId}:${date}`;
const verseById=id=>verses.find(verse=>verse.id===id);
function setReflectionButton(saved=false){const button=$('#saveReflectionButton'),field=$('#verseReflection'),text=field.value.trim();button.disabled=!text;button.innerHTML=saved?'<span aria-hidden="true">✓</span> Reflexión guardada':'Guardar reflexión';$('#reflectionCount').textContent=`${field.value.length}/${field.maxLength}`}
function resizeReflection(){const field=$('#verseReflection');field.style.height='auto';field.style.height=`${Math.min(Math.max(field.scrollHeight,82),220)}px`}
async function migrateReflections(){const marker=await AdriDB.get('settings','journalMigrationV3');if(marker)return;const [old,dailies,favorites,entries]=await Promise.all([AdriDB.all('verseReflections'),AdriDB.all('dailyVerses'),AdriDB.all('favoriteVerses'),AdriDB.all('verseJournalEntries')]);const existing=new Set(entries.map(entry=>entry.id));for(const legacy of old){const verse=verseById(legacy.verseId||legacy.id),daily=dailies.filter(item=>item.verseId===(legacy.verseId||legacy.id)).sort((a,b)=>(b.date||'').localeCompare(a.date||''))[0],fallbackDate=(legacy.updatedAt||'').slice(0,10)||app.localDate(),verseDate=daily?.date||fallbackDate,id=journalId(legacy.verseId||legacy.id,verseDate);if(existing.has(id))continue;const stamp=legacy.updatedAt||new Date().toISOString();await AdriDB.put('verseJournalEntries',{id,verseId:legacy.verseId||legacy.id,verseText:verse?.text||legacy.verseText||'',reference:verse?.reference||legacy.reference||'Referencia no disponible',translation:'Reina-Valera 1909',reflection:legacy.text||legacy.reflection||'',verseDate,createdAt:legacy.createdAt||stamp,updatedAt:stamp,isFavorite:favorites.some(item=>item.verseId===(legacy.verseId||legacy.id)),migrated:true});existing.add(id)}for(const favorite of favorites){if([...existing].some(id=>id.startsWith(`${favorite.verseId}:`)))continue;const verse=verseById(favorite.verseId),daily=dailies.filter(item=>item.verseId===favorite.verseId).sort((a,b)=>(b.date||'').localeCompare(a.date||''))[0],verseDate=daily?.date||(favorite.savedAt||'').slice(0,10)||app.localDate(),stamp=favorite.savedAt||new Date().toISOString(),id=journalId(favorite.verseId,verseDate);await AdriDB.put('verseJournalEntries',{id,verseId:favorite.verseId,verseText:verse?.text||'',reference:verse?.reference||'Referencia no disponible',translation:'Reina-Valera 1909',reflection:'',verseDate,createdAt:stamp,updatedAt:stamp,isFavorite:true,migrated:true});existing.add(id)}await AdriDB.put('settings',{id:'journalMigrationV3',value:new Date().toISOString()})}
async function renderDailyVerse(){if(verses.length!==366)return app.toast('La colección diaria no está completa.');const date=app.localDate(),verse=verseForDate();currentVerseDate=date;currentVerse=verse;let daily=await AdriDB.get('dailyVerses',date);if(!daily){daily={id:date,date,verseId:verse.id,shownAt:new Date().toISOString()};await AdriDB.put('dailyVerses',daily)}else currentVerse=verseById(daily.verseId)||verse;const [favorite,draft]=await Promise.all([AdriDB.get('favoriteVerses',currentVerse.id),AdriDB.get('settings',`verseDraft:${currentVerse.id}:${date}`)]);$('#dailyVerseText').textContent=currentVerse.text;$('#dailyVerseReference').textContent=currentVerse.reference;const save=$('#saveVerseButton');save.setAttribute('aria-pressed',String(Boolean(favorite)));save.textContent=favorite?'Guardado':'Guardar';$('#verseReflection').value=draft?.value||'';setReflectionButton();resizeReflection();await renderJournal()}
async function syncJournalFavorite(verseId,isFavorite){const entries=(await AdriDB.all('verseJournalEntries')).filter(entry=>entry.verseId===verseId);for(const entry of entries){if(!isFavorite&&!entry.reflection){await AdriDB.remove('verseJournalEntries',entry.id);continue}entry.isFavorite=isFavorite;entry.updatedAt=new Date().toISOString();await AdriDB.put('verseJournalEntries',entry)}if(isFavorite&&!entries.length){const verse=verseById(verseId),date=verseId===currentVerse?.id?currentVerseDate:app.localDate(),now=new Date().toISOString();await AdriDB.put('verseJournalEntries',{id:journalId(verseId,date),verseId,verseText:verse?.text||'',reference:verse?.reference||'Referencia no disponible',translation:'Reina-Valera 1909',reflection:'',verseDate:date,createdAt:now,updatedAt:now,isFavorite:true})}}
async function toggleFavorite(){const existing=await AdriDB.get('favoriteVerses',currentVerse.id),next=!existing;if(existing)await AdriDB.remove('favoriteVerses',currentVerse.id);else await AdriDB.put('favoriteVerses',{id:currentVerse.id,verseId:currentVerse.id,savedAt:new Date().toISOString()});await syncJournalFavorite(currentVerse.id,next);app.toast(next?'Versículo añadido a favoritos.':'Quitado de favoritos. Tu reflexión se conserva.');await renderDailyVerse()}
async function saveReflection(){const field=$('#verseReflection'),text=field.value.trim();if(!text){setReflectionButton();return}const button=$('#saveReflectionButton'),id=journalId(currentVerse.id,currentVerseDate),now=new Date().toISOString();button.disabled=true;try{const [existing,favorite]=await Promise.all([AdriDB.get('verseJournalEntries',id),AdriDB.get('favoriteVerses',currentVerse.id)]);await AdriDB.put('verseJournalEntries',{id,verseId:currentVerse.id,verseText:currentVerse.text,reference:currentVerse.reference,translation:'Reina-Valera 1909',reflection:text,verseDate:currentVerseDate,createdAt:existing?.createdAt||now,updatedAt:now,isFavorite:Boolean(favorite)});await AdriDB.put('verseReflections',{id:currentVerse.id,verseId:currentVerse.id,text,updatedAt:now});await AdriDB.remove('settings',`verseDraft:${currentVerse.id}:${currentVerseDate}`);field.value='';resizeReflection();showReflectionConfirmation(id);setReflectionButton(true);await renderJournal();setTimeout(()=>setReflectionButton(),2600)}catch(error){console.error('Guardar reflexión:',error);app.toast('No pudimos guardar tu reflexión');setReflectionButton()}}
async function shareVerse(){const text=`“${currentVerse.text}”\n${currentVerse.reference} · Reina-Valera 1909`;try{if(navigator.share)await navigator.share({title:'Una palabra para hoy',text});else if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);app.toast('Versículo copiado.')}else{const area=document.createElement('textarea');area.value=text;document.body.append(area);area.select();document.execCommand('copy');area.remove();app.toast('Versículo copiado.')}}catch(error){if(error.name!=='AbortError'){console.error(error);app.toast('No se pudo compartir ahora.')}}}
function journalDate(date){return new Intl.DateTimeFormat('es-CO',{day:'numeric',month:'long',year:'numeric'}).format(new Date(`${date}T12:00:00`)).toLocaleUpperCase('es')}
function showReflectionConfirmation(id){let confirmation=$('#reflectionConfirmation');if(!confirmation){confirmation=document.createElement('div');confirmation.id='reflectionConfirmation';confirmation.className='reflection-confirmation';$('#reflectionBox').append(confirmation)}confirmation.innerHTML=`<span><i aria-hidden="true">✓</i> Reflexión guardada en Mi cuaderno</span><button type="button" data-open-journal data-journal-entry="${escapeHtml(id)}">Ver en Mi cuaderno</button>`;confirmation.classList.add('show');setTimeout(()=>confirmation.classList.remove('show'),4200)}
function journalEntryHtml(entry){return `<article class="journal-entry${entry.id===journalHighlightId?' journal-highlight':''}" id="journal-${escapeHtml(entry.id)}" data-journal-id="${escapeHtml(entry.id)}"><header><time datetime="${escapeHtml(entry.verseDate)}">${journalDate(entry.verseDate)}</time>${entry.isFavorite?'<span class="journal-favorite" aria-label="Favorito">Favorito</span>':''}</header><blockquote>“${escapeHtml(entry.verseText||'Texto no disponible')}”</blockquote><p class="journal-reference"><strong>${escapeHtml(entry.reference||'Referencia no disponible')}</strong><span>${escapeHtml(entry.translation||'Reina-Valera 1909')}</span></p>${entry.reflection?`<div class="journal-reflection"><span>Mi reflexión</span><p>“${escapeHtml(entry.reflection)}”</p></div>`:''}${entry.migrated?'<small class="migration-note">Entrada recuperada de una versión anterior.</small>':''}<footer>${entry.reflection?`<button type="button" data-edit-journal="${escapeHtml(entry.id)}">Editar</button>`:''}<button type="button" data-share-journal="${escapeHtml(entry.id)}">Compartir</button>${entry.reflection?`<button type="button" data-delete-journal="${escapeHtml(entry.id)}">Más</button>`:''}</footer></article>`}
async function renderJournal(){const list=$('#journalList');if(!list)return;const entries=(await AdriDB.all('verseJournalEntries')).sort((a,b)=>(b.updatedAt||b.createdAt||'').localeCompare(a.updatedAt||a.createdAt||'')),query=($('#journalSearch')?.value||'').trim().toLocaleLowerCase('es');$('#journalCount').textContent=`${entries.length} ${entries.length===1?'entrada':'entradas'}`;$('#journalTools').hidden=entries.length===0;$('#journalSearch').closest('label').hidden=entries.length<8;$('.journal-filters').hidden=entries.length<3;let filtered=entries.filter(entry=>journalFilter==='reflection'?Boolean(entry.reflection):journalFilter==='favorite'?entry.isFavorite:true).filter(entry=>!query||[entry.reference,entry.verseText,entry.reflection].some(value=>(value||'').toLocaleLowerCase('es').includes(query)));list.innerHTML=!entries.length?`<div class="journal-empty"><span aria-hidden="true">“</span><h2>Tu cuaderno está esperando.</h2><p>Cuando un versículo te deje algo, puedes guardarlo aquí junto con tus palabras.</p><button type="button" class="primary" data-journal-today>Volver al versículo de hoy</button></div>`:filtered.length?filtered.map(journalEntryHtml).join(''):'<div class="journal-empty compact"><h2>No encontramos coincidencias.</h2><p>Prueba con otra palabra o cambia el filtro.</p></div>';if(journalHighlightId)requestAnimationFrame(()=>{const entry=document.getElementById(`journal-${CSS.escape(journalHighlightId)}`);entry?.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>{entry?.classList.remove('journal-highlight');journalHighlightId=''},1800)})}
function setMainView(view){document.querySelectorAll('.view').forEach(item=>item.classList.toggle('active',item.id===`view-${view}`));document.querySelectorAll('.bottom-nav button').forEach(item=>item.classList.toggle('active',view!=='cuaderno'&&item.dataset.view===view));document.querySelector('#app').scrollTo({top:0,behavior:'smooth'})}
async function openJournal(entryId='',push=true){journalReturnView=document.querySelector('.view.active')?.id.replace('view-','')||'ajustes';journalHighlightId=entryId;setMainView('cuaderno');await renderJournal();if(push)history.pushState({mareaView:'cuaderno'},'',location.href)}
function closeJournal(useHistory=true){if(useHistory&&history.state?.mareaView==='cuaderno'){history.back();return}setMainView(journalReturnView==='cuaderno'?'ajustes':journalReturnView)}
function closeJournalDialog(dialogId){const dialog=$(dialogId),opener=journalDialogOpener;if(dialog.open)dialog.close();journalDialogOpener=null;if(opener?.isConnected)requestAnimationFrame(()=>opener.focus())}
async function openJournalEditor(id,opener){const entry=await AdriDB.get('verseJournalEntries',id);if(!entry)return;journalDialogOpener=opener;const form=$('#journalEditForm');form.elements.id.value=id;form.elements.reflection.value=entry.reflection||'';$('#journalEditVerse').textContent=`“${entry.verseText}” — ${entry.reference}`;$('#journalEditDialog').showModal();form.elements.reflection.focus()}
async function saveJournalEdit(event){event.preventDefault();const form=event.currentTarget,entry=await AdriDB.get('verseJournalEntries',form.elements.id.value),text=form.elements.reflection.value.trim();if(!entry||!text)return;entry.reflection=text;entry.updatedAt=new Date().toISOString();await AdriDB.put('verseJournalEntries',entry);if(entry.verseId===currentVerse?.id){await AdriDB.put('verseReflections',{id:entry.verseId,verseId:entry.verseId,text,updatedAt:entry.updatedAt});if(entry.verseDate===currentVerseDate){$('#verseReflection').value=text;setReflectionButton();resizeReflection()}}closeJournalDialog('#journalEditDialog');journalHighlightId=entry.id;await renderJournal();app.toast('Cambios guardados')}
async function deleteJournalEntry(){const entry=await AdriDB.get('verseJournalEntries',pendingDeleteId);if(!entry)return;if(entry.isFavorite){entry.reflection='';entry.updatedAt=new Date().toISOString();await AdriDB.put('verseJournalEntries',entry)}else await AdriDB.remove('verseJournalEntries',entry.id);const sameVerse=(await AdriDB.all('verseJournalEntries')).some(item=>item.verseId===entry.verseId&&item.reflection);if(!sameVerse)await AdriDB.remove('verseReflections',entry.verseId);if(entry.verseId===currentVerse?.id&&entry.verseDate===currentVerseDate){$('#verseReflection').value='';setReflectionButton();resizeReflection()}pendingDeleteId='';closeJournalDialog('#journalDeleteDialog');await renderJournal();app.toast('Reflexión eliminada')}
async function shareText(text,title){try{if(navigator.share)await navigator.share({title,text});else if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);app.toast('Contenido copiado.')}else{const area=document.createElement('textarea');area.value=text;document.body.append(area);area.select();document.execCommand('copy');area.remove();app.toast('Contenido copiado.')}}catch(error){if(error.name!=='AbortError'){console.error('Compartir cuaderno:',error);app.toast('No se pudo compartir ahora.')}}}
async function shareJournal(choice){const entry=await AdriDB.get('verseJournalEntries',pendingShareId);if(!entry)return;const base=`“${entry.verseText}”\n${entry.reference} · ${entry.translation}`,text=choice==='both'&&entry.reflection?`${base}\n\nMi reflexión:\n${entry.reflection}`:base;closeJournalDialog('#journalShareDialog');await shareText(text,'Mi cuaderno · SpidiDay')}
function escapeHtml(text){return String(text).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}

function datesBack(count){const dates=[];for(let i=0;i<count;i++){const d=new Date();d.setDate(d.getDate()-i);dates.push(app.localDate(d))}return dates}
function shortVersion(name){const lower=name.toLocaleLowerCase('es');if(/gym|ejercicio|entren|correr|caminar|movimiento/.test(lower))return 'Haz 10 minutos de movimiento.';if(/leer|lectura|libro/.test(lower))return 'Lee solamente 2 páginas.';if(/medit|respirar|oración|orar/.test(lower))return 'Dedica 2 minutos en calma.';if(/orden|limpi|organiza/.test(lower))return 'Ordena una sola superficie.';if(/ahorr|compra/.test(lower))return 'Evita una compra opcional hoy.';return `Dedica 5 minutos a “${name}”.`}
function informativeDays(completions,expenses,shorts){return new Set([...completions.map(x=>x.date),...expenses.map(x=>x.date),...shorts.map(x=>x.date)]).size}
function rejectedKeys(feedback){const counts={};feedback.filter(f=>f.action==='rejected').forEach(f=>counts[f.patternKey]=(counts[f.patternKey]||0)+1);return new Set(Object.entries(counts).filter(([,n])=>n>=2).map(([key])=>key))}
function habitStats(routines,completions,days){return routines.map(r=>{let scheduled=0,done=0;for(const date of days){if(r.days.includes(new Date(date+'T12:00:00').getDay())){scheduled++;if(completions.some(c=>c.routineId===r.id&&c.date===date))done++}}return{routine:r,scheduled,done,missed:scheduled-done,rate:scheduled?done/scheduled:1}})}
async function buildInsight(){const date=app.localDate(),existing=await AdriDB.get('compassInsights',date);if(existing)return existing;const [routines,completions,expenses,settings,feedback,shorts,categories]=await Promise.all(['routines','completions','expenses','settings','compassFeedback','shortHabitCompletions','categories'].map(s=>AdriDB.all(s)));const days=informativeDays(completions,expenses,shorts),stage=days<7?'initial':days<21?'observation':'personalized',rejected=rejectedKeys(feedback),today=app.routinesFor(date),pending=today.filter(r=>!app.isDone(r.id,date)),budget=Number(settings.find(s=>s.id==='budget')?.value)||0,month=date.slice(0,7),spent=expenses.filter(e=>e.date.startsWith(month)).reduce((sum,e)=>sum+Number(e.amount),0),budgetPct=budget?spent/budget:0;let insight;
  if(budget&&budgetPct>=.85&&!rejected.has('budget-near')){const habit=pending[0];insight={patternKey:'budget-near',title:'Hoy conviene cuidar el margen.',copy:`Has usado ${Math.round(budgetPct*100)}% del presupuesto del mes. Una opción sencilla hoy puede darte más aire.`,why:`El cálculo usa tu presupuesto mensual y los ${expenses.filter(e=>e.date.startsWith(month)).length} gastos registrados este mes.`,relatedHabitId:habit?.id||null,shortText:habit?shortVersion(habit.name):null}}
  if(!insight&&stage==='personalized'&&!rejected.has('habit-spend-link')){const foodIds=new Set(categories.filter(c=>/comida|aliment|restaurante/i.test(c.name)).map(c=>c.id)),sampleDates=datesBack(60),rows=sampleDates.map(d=>({date:d,incomplete:app.routinesFor(d).some(r=>!completions.some(c=>c.routineId===r.id&&c.date===d)),food:expenses.filter(e=>e.date===d&&foodIds.has(e.categoryId)).reduce((s,e)=>s+Number(e.amount),0)})),miss=rows.filter(r=>r.incomplete&&r.food>0),good=rows.filter(r=>!r.incomplete&&r.food>0);if(miss.length>=4&&good.length>=4){const a=miss.reduce((s,r)=>s+r.food,0)/miss.length,b=good.reduce((s,r)=>s+r.food,0)/good.length;if(a>b*1.2){const habit=pending[0];insight={patternKey:'habit-spend-link',title:'Hoy puede ayudarte decidir antes.',copy:'En tus días con hábitos pendientes, el gasto en comida ha sido algo mayor. Preparar una opción sencilla puede cuidar ambos ritmos.',why:`Comparé ${miss.length} días con hábitos pendientes y ${good.length} días completos que tenían gastos de alimentación.`,relatedHabitId:habit?.id||null,shortText:habit?shortVersion(habit.name):null}}}}
  if(!insight&&stage!=='initial'&&!rejected.has('repeated-habit')){const stats=habitStats(routines,completions,datesBack(stage==='personalized'?60:20)).filter(s=>s.scheduled>=(stage==='personalized'?4:3)).sort((a,b)=>a.rate-b.rate),weak=stats[0];if(weak&&weak.missed>=(stage==='personalized'?3:2)){insight={patternKey:'repeated-habit',title:stage==='observation'?'Estoy empezando a notar un ritmo.':'Una versión pequeña puede sostener el hilo.',copy:stage==='observation'?`“${weak.routine.name}” ha costado un poco más últimamente. Podrías probar una versión breve, sin cambiar el hábito original.`:`“${weak.routine.name}” quedó pendiente ${weak.missed} de ${weak.scheduled} veces recientes. Hoy puede bastar con hacerlo más pequeño.`,why:`Revisé ${weak.scheduled} días en que este hábito estaba programado; se completó ${weak.done} veces.`,relatedHabitId:weak.routine.id,shortText:shortVersion(weak.routine.name)}}}
  if(!insight){const habit=pending[0];insight={patternKey:'current-day',title:pending.length?'Tu día todavía puede tomar forma.':'Hoy puedes dejar espacio para lo sencillo.',copy:pending.length?`Empieza por “${habit.name}” en una versión amable y registra cualquier gasto pendiente.`:'No hace falta optimizar nada: conserva el ritmo que ya tienes y revisa tus gastos cuando puedas.',why:days<7?`Todavía estoy conociendo tu ritmo. Solo usé el estado de hoy; hay ${days} días con información.`:'No encontré una muestra suficiente para afirmar un patrón, así que esta sugerencia usa solamente el estado actual.',relatedHabitId:habit?.id||null,shortText:habit?shortVersion(habit.name):null}}
  insight={id:date,date,stage,...insight,createdAt:new Date().toISOString(),action:null,result:null};await AdriDB.put('compassInsights',insight);return insight}
async function recordDayResult(){if(!currentInsight)return;const state=app.getState(),date=currentInsight.date,scheduled=app.routinesFor(date),full=scheduled.filter(r=>app.isDone(r.id,date)).length,partial=(state.shortHabitCompletions||[]).filter(s=>s.date===date&&s.status==='completed').length;currentInsight.result=scheduled.length&&full===scheduled.length?'complete':partial?'partial':full?'in-progress':'pending';await AdriDB.put('compassInsights',currentInsight)}
function stageLabel(stage){return stage==='initial'?'Todavía estoy conociendo tu ritmo.':stage==='observation'?'Estoy empezando a notar que…':'Una orientación basada en tu historial.'}
async function renderCompass(){currentInsight=await buildInsight();$('#compassTitle').textContent=currentInsight.title;$('#compassStage').textContent=stageLabel(currentInsight.stage);$('#compassCopy').textContent=currentInsight.copy;$('#compassWhy').textContent=currentInsight.why;$('#compassWhy').hidden=true;$('#compassWhyToggle').setAttribute('aria-expanded','false');const short=await AdriDB.get('shortHabitCompletions',`${currentInsight.date}:${currentInsight.relatedHabitId||'general'}`);$('#compassShort').hidden=!short;$('#compassShortText').textContent=short?.text||'';$('#compassActions').hidden=short?.status==='planned';$('.omit-action').hidden=!currentInsight.relatedHabitId;$('#compassFeedbackPrompt').hidden=currentInsight.action!=='activated';await recordDayResult()}
async function openCompass(){compassOpener=document.activeElement;previousOverflow=document.body.style.overflow;await renderCompass();document.body.style.overflow='hidden';$('#compassDialog').showModal()}
function closeCompass(){const dialog=$('#compassDialog'),opener=compassOpener;if(dialog.open)dialog.close();document.body.style.overflow=previousOverflow;previousOverflow='';compassOpener=null;if(opener?.isConnected)requestAnimationFrame(()=>opener.focus())}
async function saveFeedback(action,helpful=null){const item={id:`${app.localDate()}:${action}`,date:app.localDate(),insightId:currentInsight.id,patternKey:currentInsight.patternKey,action,helpful,createdAt:new Date().toISOString()};await AdriDB.put('compassFeedback',item);currentInsight.action=action;await AdriDB.put('compassInsights',currentInsight)}
async function compassAction(action){if(action==='activate'){await saveFeedback('activated');$('#compassFeedbackPrompt').hidden=false;app.toast('Plan activado para hoy.');return}if(action==='reject'){await saveFeedback('rejected',false);app.toast('Entendido. Evitaré insistir con esta orientación.');closeCompass();return}if(action==='helpful'||action==='unhelpful'){await saveFeedback(action,action==='helpful');$('#compassFeedbackPrompt').hidden=true;app.toast('Gracias. La Brújula lo tendrá en cuenta.');return}const key=`${currentInsight.date}:${currentInsight.relatedHabitId||'general'}`;if(action==='omit'){if(!currentInsight.relatedHabitId)return app.toast('No hay un hábito pendiente para omitir.');await AdriDB.put('shortHabitCompletions',{id:key,date:currentInsight.date,routineId:currentInsight.relatedHabitId,text:'Omitido conscientemente',status:'omitted',createdAt:new Date().toISOString()});await saveFeedback('omitted');await app.refresh();app.toast('Queda como omitido por hoy, sin borrar tu hábito.');closeCompass();return}if(action==='short'){let text=currentInsight.shortText;if(!text)text=prompt('¿Cuál sería una versión breve y honesta para hoy?','Dedicar 5 minutos.')?.trim();if(!text)return;await AdriDB.put('shortHabitCompletions',{id:key,date:currentInsight.date,routineId:currentInsight.relatedHabitId||null,text,status:'planned',createdAt:new Date().toISOString()});await saveFeedback('short-planned');await renderCompass();app.toast('Versión corta preparada para hoy.');return}if(action==='complete-short'){const item=await AdriDB.get('shortHabitCompletions',key);if(!item)return;item.status='completed';item.completedAt=new Date().toISOString();await AdriDB.put('shortHabitCompletions',item);await saveFeedback('short-completed',true);await app.refresh();await renderCompass();app.toast('Recuperación parcial guardada; el hábito original sigue igual.')}}

function bindEvents(){
  $('#compassButton').addEventListener('click',openCompass);$('#compassDialog').addEventListener('cancel',event=>{event.preventDefault();closeCompass()});$('#compassDialog').addEventListener('click',event=>{const close=event.target.closest('[data-compass-close]'),action=event.target.closest('[data-compass-action]');if(close)closeCompass();if(action)compassAction(action.dataset.compassAction)});$('#compassWhyToggle').addEventListener('click',()=>{const why=$('#compassWhy'),show=why.hidden;why.hidden=!show;$('#compassWhyToggle').setAttribute('aria-expanded',String(show))});
  $('#saveVerseButton').addEventListener('click',toggleFavorite);$('#shareVerseButton').addEventListener('click',shareVerse);$('#reflectionToggle').addEventListener('click',()=>{const box=$('#reflectionBox'),show=box.hidden;box.hidden=!show;$('#reflectionToggle').setAttribute('aria-expanded',String(show));if(show)$('#verseReflection').focus()});$('#saveReflectionButton').addEventListener('click',saveReflection);
  $('#verseReflection').addEventListener('input',()=>{setReflectionButton();resizeReflection();clearTimeout(draftTimer);draftTimer=setTimeout(async()=>{try{await AdriDB.put('settings',{id:`verseDraft:${currentVerse.id}:${currentVerseDate}`,value:$('#verseReflection').value,updatedAt:new Date().toISOString()})}catch(error){console.error('Guardar borrador:',error)}},350)});
  document.addEventListener('click',async event=>{const open=event.target.closest('[data-open-journal]'),close=event.target.closest('[data-close-journal]'),today=event.target.closest('[data-journal-today]'),edit=event.target.closest('[data-edit-journal]'),share=event.target.closest('[data-share-journal]'),remove=event.target.closest('[data-delete-journal]'),filter=event.target.closest('[data-journal-filter]');if(open){await openJournal(open.dataset.journalEntry||'');return}if(close){closeJournal();return}if(today){journalReturnView='hoy';setMainView('hoy');document.querySelector('.daily-word-section')?.scrollIntoView({behavior:'smooth'});return}if(edit){await openJournalEditor(edit.dataset.editJournal,edit);return}if(share){pendingShareId=share.dataset.shareJournal;journalDialogOpener=share;$('#journalShareDialog').showModal();return}if(remove){pendingDeleteId=remove.dataset.deleteJournal;journalDialogOpener=remove;$('#journalDeleteDialog').showModal();return}if(filter){journalFilter=filter.dataset.journalFilter;document.querySelectorAll('[data-journal-filter]').forEach(button=>button.classList.toggle('active',button===filter));await renderJournal()}});
  $('#journalSearch').addEventListener('input',renderJournal);$('#journalEditForm').addEventListener('submit',saveJournalEdit);$('#journalEditDialog').addEventListener('cancel',event=>{event.preventDefault();closeJournalDialog('#journalEditDialog')});$('#journalDeleteDialog').addEventListener('cancel',event=>{event.preventDefault();closeJournalDialog('#journalDeleteDialog')});$('#journalShareDialog').addEventListener('cancel',event=>{event.preventDefault();closeJournalDialog('#journalShareDialog')});
  document.addEventListener('click',event=>{if(event.target.closest('[data-close-journal-editor]'))closeJournalDialog('#journalEditDialog');if(event.target.closest('[data-close-journal-delete]')){pendingDeleteId='';closeJournalDialog('#journalDeleteDialog')}if(event.target.closest('[data-confirm-journal-delete]'))deleteJournalEntry();if(event.target.closest('[data-close-journal-share]')){pendingShareId='';closeJournalDialog('#journalShareDialog')}const choice=event.target.closest('[data-journal-share-choice]');if(choice)shareJournal(choice.dataset.journalShareChoice)});
  window.addEventListener('popstate',()=>{if($('#view-cuaderno').classList.contains('active'))closeJournal(false)});
}
async function init(){injectInterface();bindEvents();await AdriDB.open();await migrateReflections();await renderDailyVerse();document.addEventListener('marea:data-refreshed',async()=>{await migrateReflections();await renderJournal()})}
window.MareaCompassTest={verseForDate,annualOrder,buildInsight,shortVersion};
if(!window.MAREA_TEST_MODE)init().catch(error=>{console.error('Brújula SpidiDay:',error);app.toast('La Brújula no pudo iniciar.')});
})();
