(function(){
'use strict';
const db=window.AdriDB,$=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const today=()=>{const d=new Date(),x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
const cop=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const DEFAULT_ACCOUNTS=[
  {id:'account-cash',name:'Efectivo',type:'cash',icon:'💵',description:'Dinero físico'},
  {id:'account-bank',name:'Tarjeta / Cuenta',type:'bank',icon:'◉',description:'Cuenta principal'}
];
const EXPENSE_CATEGORIES=['Comida','Transporte','Gasolina','Entretenimiento','Compras','Salud','Educación','Suscripciones','Hogar','Otros'];
const INCOME_CATEGORIES=['Salario','Trabajo','Música','Venta','Regalo','Devolución','Otros'];
let data={accounts:[],transactions:[],categories:[]},filters={type:'all',period:'current',query:'',accountId:'',categoryId:'',from:'',to:''},rendering=false;

function request(req){return new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function account(id){return data.accounts.find(a=>a.id===id)}
function category(id){return data.categories.find(c=>c.id===id)}
function movementEffect(transaction,accountId){
  if(transaction.affectsBalance===false)return 0;
  const amount=Number(transaction.amount)||0;
  if(transaction.type==='income'||transaction.type==='initial')return transaction.accountId===accountId?amount:0;
  if(transaction.type==='expense')return transaction.accountId===accountId?-amount:0;
  if(transaction.type==='transfer')return (transaction.toAccountId===accountId?amount:0)-(transaction.fromAccountId===accountId?amount:0);
  return 0;
}
function calculateAccountBalance(accountId,excludeId=''){return data.transactions.filter(t=>t.id!==excludeId).reduce((sum,t)=>sum+movementEffect(t,accountId),0)}
function calculateTotalBalance(){return data.accounts.filter(a=>a.active!==false).reduce((sum,a)=>sum+calculateAccountBalance(a.id),0)}
function monthKey(date=today()){return date.slice(0,7)}
function monthly(type,month=monthKey()){return data.transactions.filter(t=>t.type===type&&t.date?.startsWith(month)).reduce((sum,t)=>sum+Number(t.amount||0),0)}
function calculateMonthlyIncome(month){return monthly('income',month)}
function calculateMonthlyExpenses(month){return monthly('expense',month)}
function calculateMonthlyBalance(month){return calculateMonthlyIncome(month)-calculateMonthlyExpenses(month)}
function toast(message){window.MareaApp?.toast?.(message)}
function runAccountingTests(){const original=data,month=monthKey(),date=`${month}-15`;try{data={accounts:[{id:'cash',active:true},{id:'bank',active:true}],categories:[],transactions:[{id:'i1',type:'initial',amount:150000,accountId:'cash',date},{id:'i2',type:'initial',amount:350000,accountId:'bank',date}]};const initialTotal=calculateTotalBalance();data.transactions.push({id:'t1',type:'transfer',amount:100000,fromAccountId:'cash',toAccountId:'bank',date});const transferTotal=calculateTotalBalance(),cashAfterTransfer=calculateAccountBalance('cash'),bankAfterTransfer=calculateAccountBalance('bank');data.transactions.push({id:'in1',type:'income',amount:200000,accountId:'cash',date},{id:'e1',type:'expense',amount:30000,accountId:'bank',date});const afterFlows=calculateTotalBalance(),income=calculateMonthlyIncome(month),expense=calculateMonthlyExpenses(month),balance=calculateMonthlyBalance(month);data.transactions=data.transactions.map(t=>t.id==='e1'?{...t,amount:20000}:t);const afterEdit=calculateTotalBalance();data.transactions=data.transactions.filter(t=>t.id!=='e1');const afterDelete=calculateTotalBalance();const result={initialTotal,transferTotal,cashAfterTransfer,bankAfterTransfer,afterFlows,income,expense,balance,afterEdit,afterDelete};const expected={initialTotal:500000,transferTotal:500000,cashAfterTransfer:50000,bankAfterTransfer:450000,afterFlows:670000,income:200000,expense:30000,balance:170000,afterEdit:680000,afterDelete:700000};for(const key of Object.keys(expected))if(result[key]!==expected[key])throw new Error(`${key}: se esperaba ${expected[key]} y se obtuvo ${result[key]}`);return {ok:true,...result}}finally{data=original}}

async function load(){data.accounts=await db.all('accounts');data.transactions=await db.all('transactions');data.categories=await db.all('financeCategories')}
async function initialize(){
  await db.open();
  if(!(await db.all('accounts')).length){for(const base of DEFAULT_ACCOUNTS)await db.put('accounts',{...base,initialBalance:0,createdAt:new Date().toISOString(),active:true})}
  if(!(await db.all('financeCategories')).length){
    for(const name of EXPENSE_CATEGORIES)await db.put('financeCategories',{id:`expense-${name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,'-')}`,name,type:'expense',active:true});
    for(const name of INCOME_CATEGORIES)await db.put('financeCategories',{id:`income-${name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,'-')}`,name,type:'income',active:true});
  }
  const marker=await db.get('settings','financeMigrationV1');
  if(!marker){
    const legacyExpenses=await db.all('expenses'),legacyCategories=await db.all('categories');
    for(const old of legacyCategories){if(!(await db.get('financeCategories',old.id)))await db.put('financeCategories',{id:old.id,name:old.name,type:'expense',active:true,legacy:true})}
    for(const old of legacyExpenses){if(!(await db.get('transactions',`legacy-expense:${old.id}`)))await db.put('transactions',{id:`legacy-expense:${old.id}`,legacyExpenseId:old.id,type:'expense',amount:Number(old.amount)||0,accountId:'account-cash',categoryId:old.categoryId,description:old.description||'Gasto anterior',note:'Importado del historial anterior de SpidiDay.',date:old.date,createdAt:old.updatedAt||new Date().toISOString(),updatedAt:new Date().toISOString(),affectsBalance:false})}
    await db.put('settings',{id:'financeMigrationV1',value:new Date().toISOString()});
  }
  await load();bind();render();
}

function validateAmount(value){const amount=Number(value);if(!Number.isFinite(amount)||amount<=0)throw new Error('Escribe un monto mayor que cero.');return amount}
async function createIncome(input){const transaction={id:uid(),type:'income',amount:validateAmount(input.amount),accountId:input.accountId,categoryId:input.categoryId||'',description:input.description.trim(),note:input.note?.trim()||'',date:input.date,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};if(!account(transaction.accountId))throw new Error('La cuenta seleccionada no existe.');await db.put('transactions',transaction);return transaction}
async function createExpense(input){const transaction={id:uid(),type:'expense',amount:validateAmount(input.amount),accountId:input.accountId,categoryId:input.categoryId||'',description:input.description.trim(),note:input.note?.trim()||'',date:input.date,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};if(!account(transaction.accountId))throw new Error('La cuenta seleccionada no existe.');await db.put('transactions',transaction);return transaction}
async function createTransfer(input,excludeId=''){const amount=validateAmount(input.amount);if(input.fromAccountId===input.toAccountId)throw new Error('Elige dos cuentas diferentes.');if(!account(input.fromAccountId)||!account(input.toAccountId))throw new Error('Una de las cuentas ya no existe.');if(amount>calculateAccountBalance(input.fromAccountId,excludeId))throw new Error('La cuenta de origen no tiene saldo suficiente para esta transferencia.');const transaction={id:uid(),type:'transfer',amount,fromAccountId:input.fromAccountId,toAccountId:input.toAccountId,description:input.description.trim()||'Transferencia entre cuentas',note:input.note?.trim()||'',date:input.date,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await db.put('transactions',transaction);return transaction}
async function createAccount(input){const name=input.name.trim(),amount=Math.max(0,Number(input.initialBalance)||0);if(!name)throw new Error('Escribe un nombre para la cuenta.');const item={id:uid(),name,type:input.type||'other',icon:input.icon?.trim()||'◇',description:input.description?.trim()||'',initialBalance:amount,createdAt:new Date().toISOString(),active:true};await db.put('accounts',item);if(amount>0)await db.put('transactions',{id:uid(),type:'initial',amount,accountId:item.id,description:'Saldo inicial',note:'Dinero existente al crear la cuenta.',date:input.date||today(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});return item}
async function updateAccount(id,input){const existing=account(id);if(!existing)throw new Error('La cuenta ya no existe.');const name=input.name.trim(),amount=Math.max(0,Number(input.initialBalance)||0),initial=data.transactions.find(t=>t.type==='initial'&&t.accountId===id);if(!name)throw new Error('Escribe un nombre para la cuenta.');await db.put('accounts',{...existing,name,type:input.type||existing.type,icon:input.icon?.trim()||'◇',description:input.description?.trim()||'',initialBalance:amount,updatedAt:new Date().toISOString()});if(amount>0)await db.put('transactions',{id:initial?.id||uid(),type:'initial',amount,accountId:id,description:'Saldo inicial',note:'Dinero existente al comenzar a usar esta cuenta.',date:initial?.date||input.date||today(),createdAt:initial?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()});else if(initial)await db.remove('transactions',initial.id)}
async function updateTransaction(id,input){const previous=data.transactions.find(t=>t.id===id);if(!previous)throw new Error('El movimiento ya no existe.');let next;if(previous.type==='transfer'){next=await buildTransfer(input,id)}else{const amount=validateAmount(input.amount);if(!account(input.accountId))throw new Error('La cuenta seleccionada no existe.');next={...previous,amount,accountId:input.accountId,categoryId:previous.type==='initial'?'':input.categoryId||'',description:input.description.trim(),note:input.note?.trim()||'',date:input.date,updatedAt:new Date().toISOString()}}await db.put('transactions',{...next,id,createdAt:previous.createdAt,affectsBalance:previous.affectsBalance});return next}
function buildTransfer(input,excludeId){const amount=validateAmount(input.amount);if(input.fromAccountId===input.toAccountId)throw new Error('Elige dos cuentas diferentes.');if(!account(input.fromAccountId)||!account(input.toAccountId))throw new Error('Una de las cuentas ya no existe.');if(amount>calculateAccountBalance(input.fromAccountId,excludeId))throw new Error('La cuenta de origen no tiene saldo suficiente.');return {...data.transactions.find(t=>t.id===excludeId),amount,fromAccountId:input.fromAccountId,toAccountId:input.toAccountId,description:input.description.trim()||'Transferencia entre cuentas',note:input.note?.trim()||'',date:input.date,updatedAt:new Date().toISOString()}}
async function deleteTransaction(id){if(!data.transactions.some(t=>t.id===id))throw new Error('El movimiento ya no existe.');await db.remove('transactions',id)}

function signMoney(value){const n=Number(value)||0;return `${n>0?'+':n<0?'−':''}${cop(Math.abs(n))}`}
function transactionValue(t){return t.type==='income'?Number(t.amount):t.type==='expense'?-Number(t.amount):0}
function transactionAccountText(t){if(t.type==='transfer')return `${account(t.fromAccountId)?.name||'Cuenta'} → ${account(t.toAccountId)?.name||'Cuenta'}`;return account(t.accountId)?.name||'Historial anterior'}
function transactionIcon(t){return t.type==='income'?'↗':t.type==='expense'?'↘':t.type==='transfer'?'↔':'◇'}
function transactionLabel(t){return t.type==='income'?'Ingreso':t.type==='expense'?'Gasto':t.type==='transfer'?'Transferencia':'Saldo inicial'}
function dateText(date){return new Intl.DateTimeFormat('es-CO',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${date}T12:00:00`))}
function accountCard(a,total){const balance=calculateAccountBalance(a.id),percent=total>0?Math.max(0,Math.round(balance/total*100)):0;return `<button class="finance-account" type="button" data-finance-account="${a.id}" aria-label="Abrir cuenta ${esc(a.name)}"><span class="account-icon">${esc(a.icon||'◇')}</span><span><strong>${esc(a.name)}</strong><small>${esc(a.description||a.type)}</small></span><b>${cop(balance)}</b><span class="account-percent">${percent}%</span></button>`}
function filteredTransactions(){let list=data.transactions.filter(t=>t.type!=='initial'||filters.type==='all');if(filters.type!=='all')list=list.filter(t=>t.type===filters.type);const now=today(),current=now.slice(0,7),d=new Date(`${now}T12:00:00`);d.setMonth(d.getMonth()-1);const previous=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;if(filters.period==='current')list=list.filter(t=>t.date?.startsWith(current));if(filters.period==='previous')list=list.filter(t=>t.date?.startsWith(previous));if(filters.period==='custom')list=list.filter(t=>(!filters.from||t.date>=filters.from)&&(!filters.to||t.date<=filters.to));if(filters.accountId)list=list.filter(t=>t.accountId===filters.accountId||t.fromAccountId===filters.accountId||t.toAccountId===filters.accountId);if(filters.categoryId)list=list.filter(t=>t.categoryId===filters.categoryId);if(filters.query)list=list.filter(t=>`${t.description} ${t.note||''}`.toLowerCase().includes(filters.query.toLowerCase()));return list.sort((a,b)=>b.date.localeCompare(a.date)||String(b.createdAt).localeCompare(String(a.createdAt)))}
function movementRow(t){const value=transactionValue(t),amount=t.type==='transfer'?cop(t.amount):signMoney(value);return `<button class="movement-row ${t.type}" type="button" data-finance-detail="${t.id}"><span class="movement-icon">${transactionIcon(t)}</span><span><strong>${esc(t.description||transactionLabel(t))}</strong><small>${esc(transactionAccountText(t))} · ${transactionLabel(t)}</small></span><b>${amount}</b></button>`}
function movementsHtml(list){if(!list.length)return '<div class="finance-empty">No hay movimientos para estos filtros.</div>';const groups=[];for(const t of list){let group=groups.find(g=>g.date===t.date);if(!group){group={date:t.date,items:[]};groups.push(group)}group.items.push(t)}return groups.map(g=>`<section class="movement-day"><h3>${g.date===today()?'Hoy':dateText(g.date)}</h3><div class="movement-list">${g.items.map(movementRow).join('')}</div></section>`).join('')}
function analysis(month){const expenses=data.transactions.filter(t=>t.type==='expense'&&t.date?.startsWith(month)),income=calculateMonthlyIncome(month),spent=calculateMonthlyExpenses(month),byCategory={};expenses.forEach(t=>byCategory[t.categoryId]=(byCategory[t.categoryId]||0)+Number(t.amount));const ranked=Object.entries(byCategory).sort((a,b)=>b[1]-a[1]),byDay={};expenses.forEach(t=>byDay[t.date]=(byDay[t.date]||0)+Number(t.amount));const peak=Object.entries(byDay).sort((a,b)=>b[1]-a[1])[0],days=new Date().getDate();return {income,spent,balance:income-spent,average:days?spent/days:0,top:ranked[0],second:ranked[1],peak}}

async function render(){if(rendering||!$('#financeTotal'))return;rendering=true;try{await load();const active=data.accounts.filter(a=>a.active!==false),total=calculateTotalBalance(),month=monthKey(),stats=analysis(month),budget=Number((await db.get('settings','budget'))?.value)||0,pct=budget?Math.round(stats.spent/budget*100):0,remaining=budget-stats.spent;
  $('#financeTotal').textContent=cop(total);$('#financeAccountCount').textContent=`Disponible entre ${active.length} ${active.length===1?'cuenta':'cuentas'}`;$('#financeAccounts').innerHTML=active.map(a=>accountCard(a,total)).join('');$('#monthIncome').textContent=signMoney(stats.income);$('#monthExpense').textContent=signMoney(-stats.spent);$('#monthBalance').textContent=signMoney(stats.balance);
  $('#financeBudgetBar').style.width=`${Math.min(pct,100)}%`;$('#financeBudgetAmount').textContent=budget?`${cop(stats.spent)} de ${cop(budget)}`:cop(stats.spent);$('#financeBudgetRemaining').textContent=budget?`${remaining>=0?'Te quedan':'Has usado por encima del presupuesto'} ${cop(Math.abs(remaining))}`:'Este mes navegas sin presupuesto.';$('#financeBudgetHelp').textContent=budget?`Has utilizado el ${pct}% de tu presupuesto.`:'Define uno para saber cuánto margen tienes.';$('#budgetButton').textContent=budget?'Cambiar presupuesto':'Crear presupuesto';
  const positive=Math.max(0,total);$('#financeDistribution').innerHTML=active.map(a=>{const balance=calculateAccountBalance(a.id),percent=positive?Math.max(0,Math.round(balance/positive*100)):0;return `<div class="distribution-row"><div><span>${esc(a.name)}</span><strong>${cop(balance)}</strong></div><div class="distribution-track"><i style="width:${Math.min(percent,100)}%"></i></div><small>${percent}%</small></div>`}).join('');
  $('#analysisSpent').textContent=cop(stats.spent);$('#analysisIncome').textContent=cop(stats.income);$('#analysisBalance').textContent=signMoney(stats.balance);$('#analysisAverage').textContent=cop(stats.average);$('#analysisTop').textContent=stats.top?`${category(stats.top[0])?.name||'Otros'} · ${cop(stats.top[1])}`:'Sin datos';$('#analysisSecond').textContent=stats.second?`${category(stats.second[0])?.name||'Otros'} · ${cop(stats.second[1])}`:'Sin datos';$('#analysisPeak').textContent=stats.peak?`${dateText(stats.peak[0])} · ${cop(stats.peak[1])}`:'Sin datos';
  fillFilters();$('#financeMovements').innerHTML=movementsHtml(filteredTransactions());renderHome(total,stats,budget);
}finally{rendering=false}}
function renderHome(total,stats,budget){if(!$('#homeRemaining'))return;$('#homeRemaining').textContent=cop(total);$('#homeSpent').textContent=signMoney(-stats.spent);const income=$('#homeIncome');if(income)income.textContent=signMoney(stats.income);$('#homeBudgetState').textContent=total?`Tu dinero está distribuido entre ${data.accounts.filter(a=>a.active!==false).length} cuentas.`:'Agrega tu saldo inicial para comenzar.';if($('#homeTideWater'))$('#homeTideWater').style.height=budget?`${Math.min(Math.max(stats.spent/budget*100,5),100)}%`:'5%'}
function fillFilters(){const accounts=data.accounts.filter(a=>a.active!==false).map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join(''),categories=data.categories.filter(c=>c.active!==false).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');const accountFilter=$('#financeAccountFilter'),categoryFilter=$('#financeCategoryFilter');if(accountFilter){const value=accountFilter.value;accountFilter.innerHTML='<option value="">Todas las cuentas</option>'+accounts;accountFilter.value=value}if(categoryFilter){const value=categoryFilter.value;categoryFilter.innerHTML='<option value="">Todas las categorías</option>'+categories;categoryFilter.value=value}}

function openMovementPicker(){$('#movementTypeDialog').showModal()}
function accountOptions(selected=''){return data.accounts.filter(a=>a.active!==false).map(a=>`<option value="${a.id}" ${a.id===selected?'selected':''}>${esc(a.name)} · ${cop(calculateAccountBalance(a.id))}</option>`).join('')}
function categoryOptions(type,selected=''){return data.categories.filter(c=>c.active!==false&&c.type===type).sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${esc(c.name)}</option>`).join('')}
function openTransaction(type,id=''){const form=$('#financeTransactionForm'),existing=data.transactions.find(t=>t.id===id);form.reset();form.elements.id.value=id;form.elements.type.value=existing?.type||type;form.elements.date.value=existing?.date||today();const actual=existing?.type||type,isTransfer=actual==='transfer',isInitial=actual==='initial';$('#financeTransactionTitle').textContent=existing?'Editar movimiento':actual==='income'?'Nuevo ingreso':actual==='expense'?'Nuevo gasto':'Nueva transferencia';$('#financeAccountField').hidden=isTransfer;$('#financeTransferFields').hidden=!isTransfer;$('#financeCategoryField').hidden=isTransfer||isInitial;$('#financeDescriptionLabel').textContent=isTransfer?'Concepto opcional':'Concepto';form.elements.description.required=!isTransfer;form.elements.accountId.innerHTML=accountOptions(existing?.accountId);form.elements.fromAccountId.innerHTML=accountOptions(existing?.fromAccountId);form.elements.toAccountId.innerHTML=accountOptions(existing?.toAccountId);form.elements.categoryId.innerHTML='<option value="">Sin categoría</option>'+categoryOptions(actual,existing?.categoryId);form.elements.amount.value=existing?.amount||'';form.elements.description.value=existing?.description||'';form.elements.note.value=existing?.note||'';$('#financeTransactionDialog').showModal()}
async function saveTransaction(event){event.preventDefault();const form=event.currentTarget,input=Object.fromEntries(new FormData(form)),id=input.id,previous=data.transactions.find(t=>t.id===id);try{if(id)await updateTransaction(id,input);else if(input.type==='income')await createIncome(input);else if(input.type==='expense')await createExpense(input);else await createTransfer(input);form.closest('dialog').close();await render();if(input.type==='expense'||previous?.type==='expense'){await window.SpidiDayClosure?.syncClosedDayExpenses?.(input.date);if(previous?.date&&previous.date!==input.date)await window.SpidiDayClosure?.syncClosedDayExpenses?.(previous.date)}window.MareaApp?.refresh?.();toast(id?'Movimiento actualizado':'Movimiento guardado')}catch(error){toast(error.message)}}
function openAccount(id=''){const form=$('#financeAccountForm'),existing=account(id),initial=data.transactions.find(t=>t.type==='initial'&&t.accountId===id);form.reset();form.elements.id.value=id;form.elements.date.value=initial?.date||today();$('#financeAccountTitle').textContent=existing?'Editar cuenta':'Nueva cuenta';if(existing){form.elements.name.value=existing.name;form.elements.type.value=existing.type;form.elements.icon.value=existing.icon||'';form.elements.description.value=existing.description||'';form.elements.initialBalance.value=initial?.amount||0}$('#financeAccountDialog').showModal()}
async function saveAccount(event){event.preventDefault();const input=Object.fromEntries(new FormData(event.currentTarget));try{if(input.id)await updateAccount(input.id,input);else await createAccount(input);event.currentTarget.closest('dialog').close();await render();toast(input.id?'Cuenta actualizada':'Cuenta creada')}catch(error){toast(error.message)}}
function openDetail(id){const t=data.transactions.find(x=>x.id===id);if(!t)return;$('#financeDetailContent').innerHTML=`<div class="detail-type ${t.type}">${transactionIcon(t)} ${transactionLabel(t)}</div><strong class="detail-amount">${t.type==='transfer'?cop(t.amount):signMoney(transactionValue(t))}</strong><dl><div><dt>${t.type==='transfer'?'Ruta':'Cuenta'}</dt><dd>${esc(transactionAccountText(t))}</dd></div>${t.categoryId?`<div><dt>Categoría</dt><dd>${esc(category(t.categoryId)?.name||'Sin categoría')}</dd></div>`:''}<div><dt>Concepto</dt><dd>${esc(t.description||transactionLabel(t))}</dd></div><div><dt>Fecha</dt><dd>${dateText(t.date)}</dd></div>${t.note?`<div><dt>Nota</dt><dd>${esc(t.note)}</dd></div>`:''}</dl>`;$('#financeEditMovement').dataset.id=id;$('#financeDeleteMovement').dataset.id=id;$('#financeMovementDetail').showModal()}
async function removeFromDetail(){const id=$('#financeDeleteMovement').dataset.id,previous=data.transactions.find(t=>t.id===id);if(!confirm('¿Eliminar este movimiento? El saldo se recalculará automáticamente.'))return;try{await deleteTransaction(id);$('#financeMovementDetail').close();await render();if(previous?.type==='expense')await window.SpidiDayClosure?.syncClosedDayExpenses?.(previous.date);window.MareaApp?.refresh?.();toast('Movimiento eliminado y saldo actualizado')}catch(error){toast(error.message)}}
function exportCsv(){const rows=[['Fecha','Tipo','Monto','Cuenta','Categoría','Concepto','Nota'],...filteredTransactions().map(t=>[t.date,transactionLabel(t),t.amount,transactionAccountText(t),category(t.categoryId)?.name||'',t.description||'',t.note||''])],csv='\uFEFF'+rows.map(row=>row.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`spididay-movimientos-${today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function bind(){if(document.body.dataset.financeBound)return;document.body.dataset.financeBound='true';document.addEventListener('click',event=>{const target=event.target.closest('button,[data-finance-type],[data-finance-detail],[data-finance-account]');if(!target)return;if(target.id==='financeMovementButton')openMovementPicker();if(target.id==='financeAddAccount')openAccount();if(target.dataset.financeAccount)openAccount(target.dataset.financeAccount);if(target.dataset.financeType){$('#movementTypeDialog').close();openTransaction(target.dataset.financeType)}if(target.dataset.financeDetail)openDetail(target.dataset.financeDetail);if(target.id==='financeEditMovement'){const id=target.dataset.id,t=data.transactions.find(x=>x.id===id);$('#financeMovementDetail').close();openTransaction(t.type,id)}if(target.id==='financeDeleteMovement')removeFromDetail();if(target.dataset.financeFilter){filters.type=target.dataset.financeFilter;$$('[data-finance-filter]').forEach(b=>b.classList.toggle('active',b===target));render()}if(target.id==='financeExport')exportCsv()});$('#financeTransactionForm')?.addEventListener('submit',saveTransaction);$('#financeAccountForm')?.addEventListener('submit',saveAccount);$('#financeSearch')?.addEventListener('input',e=>{filters.query=e.target.value.trim();render()});$('#financePeriod')?.addEventListener('change',e=>{filters.period=e.target.value;$('#financeCustomRange').hidden=e.target.value!=='custom';render()});$('#financeAccountFilter')?.addEventListener('change',e=>{filters.accountId=e.target.value;render()});$('#financeCategoryFilter')?.addEventListener('change',e=>{filters.categoryId=e.target.value;render()});$('#financeFrom')?.addEventListener('change',e=>{filters.from=e.target.value;render()});$('#financeTo')?.addEventListener('change',e=>{filters.to=e.target.value;render()})}

window.SpidiFinance={initialize,render,createIncome,createExpense,createTransfer,createAccount,updateAccount,updateTransaction,deleteTransaction,calculateAccountBalance,calculateTotalBalance,calculateMonthlyIncome,calculateMonthlyExpenses,calculateMonthlyBalance,runAccountingTests,getData:()=>data};
if(!window.__SPIDIDAY_TEST__)initialize().catch(error=>{console.error('Finanzas:',error);toast('No se pudo abrir el módulo Dinero.')});
})();
